In [ ]:
# Question: walk in a 2 d space:  find possible paths person can move only 1 unit at a time m is moves for 2 moves
# we get 6 possilbe answers 
# and grid lenth is [0,1,2] so person can only moves in between 0 and 2
        :- start point:      (0,0)
First possible moves: points (0,0)-->(0,1)
                             (0,0)-->(1,0)
Second possible moves: points(0,0)-->(0,1)-->(0,0)
                             (0,0)-->(0,1)-->(0,2)
                             (0,0)-->(0,1)-->(1,1)
                             (0,0)-->(1,0)-->(0,0)
                             (0,0)-->(1,0)-->(2,0)
                             (0,0)-->(1,0)-->(1,1)  
                        

In [ ]:
# now its 4 D space moves m = 10
# grid length = [0,1,2,3,4,5,6,7,9]
#start point [0,0,0,0] find all possible valid paths
# how Cuda is used
# how code is optimized

In [29]:
import numpy as np 
import itertools
from collections import Counter
import pandas as pd


def checkdigitsame(arr1,arr2,dimension):
    counter=0
    for i in range(0,dimension):
        if arr1[i]==arr2[i]:
            counter=counter+1
    if counter==dimension-1:
        return True
    else:
        return False

def possiblepath(startnode,finalcombinationnp,dimension):
    templist=[]
    for j in range(0,len(finalcombinationnp)):
        if checkdigitsame(startnode,finalcombinationnp[j],dimension)==True:
            if sum(startnode-finalcombinationnp[j])==1 or sum(startnode-finalcombinationnp[j])==-1:
                #print(finalcombinationnp[j])
                templist.append(list(finalcombinationnp[j]))
    return templist         

def allpossiblepath(patharray):
    # patharray is numpy array
    templist=[]
    for rt in range(0,len(patharray)):
        tempnp1=possiblepath(patharray[rt],finalcombinationnp,dimension)
        templist.extend(tempnp1)
    return templist

x = [0, 1, 2,3,4,5,6,7,8,9]
finalcombinationlist=[p for p in itertools.product(x, repeat=2)]
finalcombinationnp=np.asarray(finalcombinationlist)    
m=8
dimension=2
tempnp=possiblepath(finalcombinationnp[0],finalcombinationnp,dimension)

for h in range(0,m-1):
    templist=allpossiblepath(tempnp)
    tempnp=np.asarray(templist)
    b = {}
    for i in range(0, len(templist), 1):
        if tuple(templist[i]) in b:
            b[tuple(templist[i])] +=1
        else:
            b[tuple(templist[i])]=1
            
    print(b,"Hello")
    



{(0, 0): 2, (0, 2): 1, (1, 1): 2, (2, 0): 1} Hello
{(0, 1): 5, (1, 0): 5, (0, 3): 1, (1, 2): 3, (2, 1): 3, (3, 0): 1} Hello
{(0, 0): 10, (0, 2): 9, (1, 1): 16, (2, 0): 9, (0, 4): 1, (1, 3): 4, (2, 2): 6, (3, 1): 4, (4, 0): 1} Hello
{(0, 1): 35, (1, 0): 35, (0, 3): 14, (1, 2): 35, (2, 1): 35, (3, 0): 14, (0, 5): 1, (1, 4): 5, (2, 3): 10, (3, 2): 10, (4, 1): 5, (5, 0): 1} Hello
{(0, 0): 70, (0, 2): 84, (1, 1): 140, (2, 0): 84, (0, 4): 20, (1, 3): 64, (2, 2): 90, (3, 1): 64, (4, 0): 20, (0, 6): 1, (1, 5): 6, (2, 4): 15, (3, 3): 20, (4, 2): 15, (5, 1): 6, (6, 0): 1} Hello
{(0, 1): 294, (1, 0): 294, (0, 3): 168, (1, 2): 378, (2, 1): 378, (3, 0): 168, (0, 5): 27, (1, 4): 105, (2, 3): 189, (3, 2): 189, (4, 1): 105, (5, 0): 27, (0, 7): 1, (1, 6): 7, (2, 5): 21, (3, 4): 35, (4, 3): 35, (5, 2): 21, (6, 1): 7, (7, 0): 1} Hello
{(0, 0): 588, (0, 2): 840, (1, 1): 1344, (2, 0): 840, (0, 4): 300, (1, 3): 840, (2, 2): 1134, (3, 1): 840, (4, 0): 300, (0, 6): 35, (1, 5): 160, (2, 4): 350, (3, 3): 448, (

In [65]:
test_dict1={(0, 0): 2, (0, 2): 1, (1, 1): 2, (2, 0): 1}
z=test_dict1.copy()
test_dict2={(0, 0): 1, (0, 2): 2, (1, 1): 2, (3, 0): 1}
z.update(test_dict2)
#dict(z.items()+z1.items())
# Using Counter() + "-" operator 
# Subtraction of dictionaries 
#temp1 = Counter(z) 
res = {key: test_dict2.get(key, 0) + test_dict1.get(key, 0) 
                       for key in z.keys()} 
  
# printing result  
print("The summation dictionary is : " + str(res)) 
z

The summation dictionary is : {(0, 0): 3, (0, 2): 3, (1, 1): 4, (2, 0): 1, (3, 0): 1}


{(0, 0): 1, (0, 2): 2, (1, 1): 2, (2, 0): 1, (3, 0): 1}

In [51]:
test_dict1

{(0, 0): 1, (0, 2): 2, (1, 1): 2, (2, 0): 1, (3, 0): 1}

In [5]:
len(tempnp)

200

In [62]:
import numpy as np
from numba import njit, cuda 
from timeit import default_timer as timer
start = timer()  
    
startpoint=[0,0,0,0]
postivearray=[[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]]
postivearraynp=np.asarray(postivearray)
neagativearray=[[0,0,0,-1],[0,0,-1,0],[0,-1,0,0],[-1,0,0,0]]
neagativearraynp=np.asarray(neagativearray)
snp=np.asarray(startpoint)

@njit
def addarray(snp):
    templist=[]
    for i in range(0,len(snp)):
        checkarray=snp+postivearraynp[i]
        if ((checkarray<10).sum())==4:
            templist.append(list(checkarray))
    return templist 
@njit
def subarray(snp):
    templist=[]
    for i in range(0,len(snp)):
        checkarray=snp+neagativearraynp[i]
        if ((checkarray>=0).sum())==4:
            templist.append(list(checkarray))
    return templist 
@njit
def finalarray(snp):
    return subarray(snp)+addarray(snp)

def allpossiblepath1(patharray):
    # patharray is numpy array
    templist=[]
    for rt in range(0,len(patharray)):
        tempnp1=finalarray(patharray[rt])
        templist.extend(tempnp1)
    return templist
def allpossiblepath1(Uniquedict):
    
m=2
tempnp=np.asarray(finalarray(snp))
print(tempnp)
for h in range(0,m-1):
    templist=allpossiblepath1(tempnp)
    tempnp=np.asarray(templist)
    b = {}
    for i in range(0, len(templist), 1):
        if tuple(templist[i]) in b:
            b[tuple(templist[i])] +=1
        else:
            b[tuple(templist[i])]=1
            
    print(b,"Hello")
print("with GPU:", timer()-start)      

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
{(0, 0, 0, 0): 4, (0, 0, 0, 2): 1, (0, 0, 1, 1): 2, (0, 1, 0, 1): 2, (1, 0, 0, 1): 2, (0, 0, 2, 0): 1, (0, 1, 1, 0): 2, (1, 0, 1, 0): 2, (0, 2, 0, 0): 1, (1, 1, 0, 0): 2, (2, 0, 0, 0): 1} Hello
with GPU: 0.7384677459485829


In [207]:
def finalarray(snp):
    return subarray(snp)+addarray(snp)

In [1]:
def allpossiblepath1(patharray):
    # patharray is numpy array
    templist=[]
    for rt in range(0,len(patharray)):
        tempnp1=finalarray(patharray[rt])
        templist.extend(tempnp1)
    return templist
m=6
tempnp=np.asarray(finalarray(snp))
for h in range(0,m-1):
    templist=allpossiblepath1(tempnp)
    tempnp=np.asarray(templist)
    print(len(tempnp))

NameError: name 'np' is not defined

In [200]:
20
108
624
3760
23480
150500
986440
6580224
44569724


64
512
4092
32640
259664

64
508
3992
31060
239600

[[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]]

In [194]:
addarray(snp)

[[0, 0, 1, 1], [0, 0, 2, 0], [0, 1, 1, 0], [1, 0, 1, 0]]

In [187]:
(checkarray>=0).sum()

3

In [1]:
from numba import jit, cuda 
import numpy as np 
# to measure exec time 
from timeit import default_timer as timer    
  
# normal function to run on cpu 
def func(a):                                 
    for i in range(10000000): 
        a[i]+= 1      
  
# function optimized to run on gpu  
@jit                       
def func2(a): 
    for i in range(10000000): 
        a[i]+= 1
if __name__=="__main__": 
    n = 10000000                            
    a = np.ones(n, dtype = np.float64) 
    b = np.ones(n, dtype = np.float32) 
      
    start = timer() 
    func(a) 
    print("without GPU:", timer()-start)     
      
    start = timer() 
    func2(a) 
    print("with GPU:", timer()-start)

without GPU: 6.383536042179912
with GPU: 0.8389982068911195


In [12]:
startpoint=[3,3,3,3]
postivearray=[[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]]
neagativearray=[[0,0,0,-1],[0,0,-1,0],[0,-1,0,0],[-1,0,0,0]]
snp=np.asarray(startpoint)
postivearray=[[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]]
postivearraynp=np.asarray(postivearray)

In [77]:
start=timer()
for i in range(100000):
    t=postivearraynp+snp
print("with GPU:", timer()-start) 

with GPU: 0.1748398318886757


In [78]:
start=timer()
for i in range(100000):
    t=snp+postivearray
print("with GPU:", timer()-start) 

with GPU: 0.6206197468563914


In [79]:
t

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [ ]:
import numpy as np
from numba import njit, cuda 
start = timer()  
    
startpoint=[0,0,0,0]
postivearray=[[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]]
postivearraynp=np.asarray(postivearray)
neagativearray=[[0,0,0,-1],[0,0,-1,0],[0,-1,0,0],[-1,0,0,0]]
neagativearraynp=np.asarray(neagativearray)
snp=np.asarray(startpoint)

@njit
def finalarray(snp):
    templist=[]
    templist1=[]
    for i in range(0,len(snp)):
        checkarrayPos=snp+postivearraynp[i]
        checkarrayNeg=snp+neagativearraynp[i]
        if ((checkarrayPos<10).sum())==4:
            templist.append(list(checkarrayPos))

        if ((checkarrayNeg>=0).sum())==4:
            templist1.append(list(checkarrayNeg))
    return templist+templist1 

def allpossiblepath1(patharray):
    # patharray is numpy array
    templist=[]
    for rt in range(0,len(patharray)):
        tempnp1=finalarray(patharray[rt])
        templist.extend(tempnp1)
    return templist
m=10
tempnp=np.asarray(finalarray(snp))
for h in range(0,m-1):
    templist=allpossiblepath1(tempnp)
    tempnp=np.asarray(templist)
    print(len(tempnp))
print("with GPU:", timer()-start)      

64
512
4096
32764
261988
2093580
16714512


In [64]:
import numpy as np
from numba import njit, cuda 
from timeit import default_timer as timer
start = timer()  
    
startpoint=[0,0,0,0]
postivearray=[[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]]
postivearraynp=np.asarray(postivearray)
neagativearray=[[0,0,0,-1],[0,0,-1,0],[0,-1,0,0],[-1,0,0,0]]
neagativearraynp=np.asarray(neagativearray)
snp=np.asarray(startpoint)

@njit
def addarray(snp):
    templist=[]
    for i in range(0,len(snp)):
        checkarray=snp+postivearraynp[i]
        if ((checkarray<10).sum())==4:
            templist.append(list(checkarray))
    return templist 
@njit
def subarray(snp):
    templist=[]
    for i in range(0,len(snp)):
        checkarray=snp+neagativearraynp[i]
        if ((checkarray>=0).sum())==4:
            templist.append(list(checkarray))
    return templist 
@njit
def finalarray(snp):
    return subarray(snp)+addarray(snp)

def allpossiblepath1(patharray):
    # patharray is numpy array
    templist=[]
    for rt in range(0,len(patharray)):
        tempnp1=finalarray(patharray[rt])
        tempdict = {}
        for i in range(0, len(tempnp1), 1):
            if tuple(tempnp1[i]) in b:
                tempdict[tuple(tempnp1[i])] +=1
            else:
                tempdict[tuple(tempnp1[i])]=1
                
        templist.extend(tempnp1)
    return templist

def allpossiblepath2(tempdictout):
    templist=[]
    finaldict={}
    for key in tempdictout:
        tempdict = {}
        tempnp1=finalarray(list(key))
        for i in range(0, len(tempnp1),1):
            tempdict[tuple(tempnp1[i])]=1*int(tempdictout[key])
        z=tempdict.copy()
        z.update(finaldict)
        res = {key: finaldict.get(key, 0) + tempdict.get(key, 0) 
                       for key in z.keys()} 
    return res
m=2

tempnp=np.asarray(finalarray(snp))

print(tempnp)
for h in range(0,m-1):
    templist=allpossiblepath1(tempnp)
    tempdict = {}
    for i in range(0, len(templist), 1):
        if tuple(templist[i]) in b:
            tempdict[tuple(templist[i])] +=1
        else:
            tempdict[tuple(templist[i])]=1
    tempnp=np.asarray(templist)
    b = {}
    for i in range(0, len(templist), 1):
        if tuple(templist[i]) in b:
            b[tuple(templist[i])] +=1
        else:
            b[tuple(templist[i])]=1
            
    print(b,"Hello")
print("with GPU:", timer()-start)      

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
{(0, 0, 0, 0): 4, (0, 0, 0, 2): 1, (0, 0, 1, 1): 2, (0, 1, 0, 1): 2, (1, 0, 0, 1): 2, (0, 0, 2, 0): 1, (0, 1, 1, 0): 2, (1, 0, 1, 0): 2, (0, 2, 0, 0): 1, (1, 1, 0, 0): 2, (2, 0, 0, 0): 1} Hello
with GPU: 0.6747189299203455


In [135]:
#### This is the final code 


import numpy as np
from numba import njit, cuda 
from timeit import default_timer as timer
start = timer()  

dimension=4
startpoint=(0,0,0,0)
postivearray=[]
negativearray=[]
## generating positive and negative list to move 1 step
for i in range(0,len(startpoint)):
    templist=list(startpoint)
    templist[i]=templist[i]+1
    postivearray.append(templist)
    
    templist1=list(startpoint)
    templist1[i]=templist1[i]-1
    negativearray.append(templist1)
    
postivearraynp=np.asarray(postivearray)
neagativearraynp=np.asarray(neagativearray)
snp=np.asarray(startpoint)

@njit # this is to opttmize using cuda
def addarray(snp): # return all possilbe moves in positive direction
    templist=[]
    for i in range(0,len(snp)):
        checkarray=snp+postivearraynp[i]
        if ((checkarray<10).sum())==4:
            templist.append(list(checkarray))
    return templist 
@njit
def subarray(snp): # return all possilbe moves in negative direction
    templist=[]
    for i in range(0,len(snp)):
        checkarray=snp+neagativearraynp[i]
        if ((checkarray>=0).sum())==4:
            templist.append(list(checkarray))
    return templist 
@njit
def finalarray(snp):
    return subarray(snp)+addarray(snp)
def allpossiblepath2(tempdictout):
    templist=[]
    finaldict={}
    for key in tempdictout:
        tempdict = {}
        tempnp1=finalarray(np.asarray(list(key)))
        for i in range(0, len(tempnp1),1):
            tempdict[tuple(tempnp1[i])]=1*int(tempdictout[key])
        z=tempdict.copy()
        z.update(finaldict)
        finaldict = {key: finaldict.get(key, 0) + tempdict.get(key, 0) 
                       for key in z.keys()} 
    return finaldict
templist=finalarray(snp)
b={}
for i in range(0, len(templist), 1):
    b[tuple(templist[i])]=1
m=10
for h in range(0,m-1):
    finaltempdict=allpossiblepath2(b)
    b=finaltempdict
    print(sum(b.values()))
print("with GPU:", timer()-start)      

20
108
624
3760
23480
150500
986440
6580224
44569724
with GPU: 1.024014559108764
